[databases]
# Map incoming connections for the wallet database to the cloud PostgreSQL instance
thor001db = host=34.35.129.134 port=5432 dbname=thor001db user=thoro1 password='K"Pn9^Qf]o-7E9C#'

[pgbouncer]
listen_addr = 0.0.0.0
listen_port = 5432
auth_type = scram-sha-256
auth_file = /etc/pgbouncer/userlist.txt
pool_mode = transaction
max_client_conn = 1000
default_pool_size = 50
min_pool_size = 10
reserve_pool_size = 5
ignore_startup_parameters = extra_float_digits

# Admin console config
admin_users = postgres
