# Generated by Django 6.0.6 on 2026-06-25 18:59

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default Wallet', max_length=100)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'currency'], name='wallet_wall_user_id_098bf8_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'currency', 'name'), name='unique_user_wallet_per_currency_name')],
            },
        ),
    ]
